//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeBeachV3._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeachInfoV3_1
    {
        public double beachID { get; set; }
        public string beachName { get; set; }
        public string beachAddress { get; set; }
        public string region { get; set; }
        public string beachSuburb { get; set; }
        public Nullable<double> postcode { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string patrol { get; set; }
        public string patrolTime { get; set; }
        public string surfLevel { get; set; }
        public string swimLevel { get; set; }
        public string drowning { get; set; }
        public string waterQuality { get; set; }
        public string picturePath
        {
            get
            {
                return this.beachID + ".jpg";
            }
        }
    }
}
